---
- name: Restart iptable
  service: name=iptables state=restart enabled=yes
- name: Reload firewalld
  service: firewall-cmd --reload
- name: Run update-grub
  shell: "{{update_grub}}"
  when: ansible_distribution_major_version|int > 6