- hosts: java-servers
  vars:
    home: /root
    jdk_file: jdk-11.0.2_linux-x64_bin
  tasks:
  #   - name: genenrate rsa
  #     shell: ssh-keygen -t rsa
  #     when: master is defined
    
    - name: ssh-copy-id
      shell: ssh-copy-id -i ~/.ssh/id_rsa.pub
      when: slave is defined
      tags:
        - rsa
    
    - name: chmod 600 for rsa
      shell: chmod 0600 ~/.ssh/authorized_keys
      tags:
        - rsa
    
    - name: copy jdk to clients
      unarchive:
        src: ../files/{{jdk_file}}.tar.gz
        dest: "{{home}}"
      tags:
        - install_java
    
    - name: setup JAVA_HOME
      shell: echo "export JAVA_HOME={{home}}/{{jdk_file}}" >> ~/.bashrc && source ~/.bashrc
      tags:
        - config_java
        - install_java
    
    # need to install pyexpected in target machines
    - name: rsa generation
      expect:
        command: ssh-keygen -t rsa 
        echo: yes
        creates: /root/.ssh/id_rsa
        responses:
          "file": "" ## Enter file in which to save the key (/root/.ssh/id_rsa)
          "Overwrite": "Y" ## Overwrite (y/n)? 
          "passphrase": "" ## Enter passphrase (empty for no passphrase)
      tags:
        - generate_ssh
    
    - name: copy to sshpass rsa script to all machines
      template: 
        src: ../templates/copy_ssh.sh
        dest: /data/copy_ssh.sh
      tags:
        - copy_ssh
    - name: run copy ssh configuration
      shell: sh copy_ssh.sh
      args:
        chdir: /data
      tags:
        - pass_ssh