---
- name: Update apt cache
  apt:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install basic tools
  apt:
    name: "{{ item }}"
    state: present
    force: yes
  become: yes
  with_items:
    - cli-common
    - zsh
    - make
    - vim
    - tmux
    - ranger
    - p7zip

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  become: yes
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- import_tasks: docker-compose.yml
  when: docker_install_compose
