- hosts: prometheus-nodes
  vars:
    prometheus_root_dir: /data/prometheus
    workspace: /data/prometheus/node_exporter-0.15.1.linux-amd64
  tasks:
    - name: create prometheus directory structure
      file: >
        state=directory
        path={{ item }}
        owner=root
        group=root
      with_items:
        - "{{ prometheus_root_dir }}"
        # - "{{ prometheus_bin_dir }}"
        # - "{{ prometheus_dist_dir }}"
        # - "{{ prometheus_config_dir }}"
        # - "{{ prometheus_db_dir }}"
      tags:
        - install-node-exporter
    - name: install node-exporter
      unarchive:
        src: ../files/node_exporter-0.15.1.linux-amd64.tar.gz
        dest: "{{ prometheus_root_dir }}"
      tags:
        - install-nodeexporter


    - name: stop node-exporter
      shell: ps aux | grep node_exporter | grep -v 'grep' | awk '{ print $2}' | xargs kill -9
      tags:
        - stop-nodeexporter
        - restart-nodeexporter
      ignore_errors: true

    - name: start node-exporter
      shell: setsid ./node_exporter &
      args:
        chdir: "{{workspace}}"
      tags:
          - start-nodeexporter
          - restart-nodeexporter