db:
  image: mysql
  volumes:
    - "/var/data/mysql:/var/lib/mysql"
  ports:
    - 3306:3306
  environment: 
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: cibott
    MYSQL_PASSWORD: password

web:
  image: web-app-0.1
  ports:
    - "9090:9090"
  linkes:
    - db